name = "NewtonsMethod"
uuid = "70774902-ec4a-11e9-08ef-6ddf5a464080"
authors = ["PooyaFa <pooyaravari@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
